"""user Migration

Revision ID: 5878ed610eae
Revises: 
Create Date: 2020-10-24 16:02:17.097931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5878ed610eae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('emailAddress', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_emailAddress'), 'users', ['emailAddress'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_emailAddress'), table_name='users')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'password')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'emailAddress')
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###
