"""model modification

Revision ID: 612e6e88433d
Revises: 5878ed610eae
Create Date: 2020-10-24 20:20:04.427579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612e6e88433d'
down_revision = '5878ed610eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_emailAddress', table_name='users')
    op.drop_column('users', 'emailAddress')
    op.drop_column('users', 'password')
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emailAddress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_emailAddress', 'users', ['emailAddress'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
